version: '3.7'

services:

  node:
    image: mhilker/murmur-dashboard:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MURMUR_HOST=mumble
      - MURMUR_PORT=6502
