version: '3.7'

services:

  node:
    image: mhilker/murmur-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MURMUR_HOST=mumble
      - MURMUR_PORT=6502
